from enum import Enum

class ReadinessLevel(str, Enum):
    NOT_READY = "NOT_READY"
    SHADOW_READY = "SHADOW_READY"
    HUMAN_APPROVAL_READY = "HUMAN_APPROVAL_READY"
    SANDBOX_AUTONOMOUS_READY = "SANDBOX_AUTONOMOUS_READY"
    PRODUCTION_CANDIDATE = "PRODUCTION_CANDIDATE"
