from typing import Set

CHART_OF_ACCOUNTS: Set[str] = {
    "BANK_CASH_GATEWAY_A",
    "BANK_CASH_GATEWAY_B",
    "BANK_CASH_GATEWAY_C",
    "BANK_CASH_GATEWAY_D",
    "MERCHANT_SETTLEMENT_CLEARING",
    "MERCHANT_RECEIVABLES",
    "CUSTOMER_DEPOSIT_ACCOUNT",
    "DISPUTED_ESCROW_ACCOUNT",
    "REFUND_CLEARING_ACCOUNT",
    "PLATFORM_PROCESSING_FEE_REVENUE",
    "OPERATIONAL_RECOVERY_EXPENSE"
}
