from enum import Enum
from typing import Dict, Any, List

class AdversarialPolicy(str, Enum):
    CONTROL_NO_ULTRON = "CONTROL_NO_ULTRON"
    RULE_BASED = "RULE_BASED"
    ULTRON_LLM_OFF = "ULTRON_LLM_OFF"
    ULTRON_LLM_ON = "ULTRON_LLM_ON"
    ULTRON_FULL = "ULTRON_FULL"
    CONSERVATIVE = "CONSERVATIVE"
    AGGRESSIVE_DUNNING = "AGGRESSIVE_DUNNING"
    ALWAYS_WAIT = "ALWAYS_WAIT"
    ALWAYS_RETRY = "ALWAYS_RETRY"
    ALWAYS_CONTACT = "ALWAYS_CONTACT"
    ALWAYS_SWITCH_GATEWAY = "ALWAYS_SWITCH_GATEWAY"

ALL_V15_POLICIES = [p.value for p in AdversarialPolicy]
