import { DatabaseAdapter } from '../db/adapter.js';
import { RecoveryOpportunity } from '../types/index.js';

export interface PreventedInterventionRecord {
  id: string;
  opportunity_id: string;
  tenant_id: string;
  prevention_reason: string;
  messaging_fee_saved_paise: number;
  provider_fee_saved_paise: number;
  goodwill_saved_paise: number;
  total_capital_saved_paise: number;
  timestamp: string;
}

export interface AntiBlastSummary {
  total_prevented: number;
  messaging_saved_paise: number;
  provider_saved_paise: number;
  goodwill_saved_paise: number;
  total_capital_saved_paise: number;
  total_capital_saved_display: string;
}

export class AntiBlastEngine {
  private static WHATSAPP_FEE_PAISE = 85; // ₹0.85 Meta WhatsApp Utility fee
  private static RAZORPAY_LINK_FEE_PAISE = 400; // ₹4.00 Razorpay link operational overhead

  public static async initTable(db?: DatabaseAdapter): Promise<void> {
    const adapter = db || DatabaseAdapter.getInstance();
    await adapter.execute(`
      CREATE TABLE IF NOT EXISTS interventions_prevented (
        id TEXT PRIMARY KEY,
        opportunity_id TEXT NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'tenant_system_default',
        prevention_reason TEXT NOT NULL,
        messaging_fee_saved_paise INTEGER NOT NULL,
        provider_fee_saved_paise INTEGER NOT NULL,
        goodwill_saved_paise INTEGER NOT NULL,
        total_capital_saved_paise INTEGER NOT NULL,
        timestamp TEXT NOT NULL
      );
    `);
  }

  /**
   * Calculates the exact financial and customer goodwill savings generated by refraining from an action.
   */
  public static calculateSavings(opp: RecoveryOpportunity, reason: string): {
    messaging_saved: number;
    provider_saved: number;
    goodwill_saved: number;
    total_saved: number;
  } {
    const messaging_saved = this.WHATSAPP_FEE_PAISE;
    const provider_saved = this.RAZORPAY_LINK_FEE_PAISE;

    let goodwill_saved = 0;
    if (opp.decline_type === 'hard') {
      // Hard fraud / stolen card blocks: avoiding contact saves merchant from dispute & customer irritation
      goodwill_saved = 5000; // ₹50.00 customer lifetime goodwill preservation
    } else if (opp.attempt_count >= 3) {
      // Contacting a customer 3+ times triggers spam reports and unsubscriptions
      goodwill_saved = 1500; // ₹15.00 churn mitigation
    } else if (reason.includes('timeout') || reason.includes('gateway')) {
      // Bank gateway downtime: contacting when payment will recover naturally prevents duplicate payments
      goodwill_saved = 1000; // ₹10.00 customer confusion prevention
    } else {
      goodwill_saved = 500; // ₹5.00 baseline brand hygiene
    }

    const total_saved = messaging_saved + provider_saved + goodwill_saved;

    return {
      messaging_saved,
      provider_saved,
      goodwill_saved,
      total_saved,
    };
  }

  /**
   * Records a prevented intervention when an opportunity is ABSTAINed or BLOCKED
   */
  public static async recordPreventedIntervention(
    opp: RecoveryOpportunity,
    reason: string
  ): Promise<PreventedInterventionRecord> {
    const adapter = DatabaseAdapter.getInstance();
    await this.initTable(adapter);

    const savings = this.calculateSavings(opp, reason);
    const id = `prev_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const tenantId = (opp as any).tenant_id || 'tenant_system_default';
    const now = new Date().toISOString();

    await adapter.execute(
      `INSERT INTO interventions_prevented (
        id, opportunity_id, tenant_id, prevention_reason,
        messaging_fee_saved_paise, provider_fee_saved_paise, goodwill_saved_paise,
        total_capital_saved_paise, timestamp
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);`,
      [
        id,
        opp.id,
        tenantId,
        reason,
        savings.messaging_saved,
        savings.provider_saved,
        savings.goodwill_saved,
        savings.total_saved,
        now,
      ]
    );

    return {
      id,
      opportunity_id: opp.id,
      tenant_id: tenantId,
      prevention_reason: reason,
      messaging_fee_saved_paise: savings.messaging_saved,
      provider_fee_saved_paise: savings.provider_saved,
      goodwill_saved_paise: savings.goodwill_saved,
      total_capital_saved_paise: savings.total_saved,
      timestamp: now,
    };
  }

  /**
   * Retrieves aggregate anti-blast metrics across the portfolio or for a tenant
   */
  public static async getAntiBlastSummary(tenantId?: string): Promise<AntiBlastSummary> {
    const adapter = DatabaseAdapter.getInstance();
    await this.initTable(adapter);

    let query = `
      SELECT 
        COUNT(*) as total_prevented,
        COALESCE(SUM(messaging_fee_saved_paise), 0) as messaging_saved_paise,
        COALESCE(SUM(provider_fee_saved_paise), 0) as provider_saved_paise,
        COALESCE(SUM(goodwill_saved_paise), 0) as goodwill_saved_paise,
        COALESCE(SUM(total_capital_saved_paise), 0) as total_capital_saved_paise
      FROM interventions_prevented
    `;
    const params: any[] = [];
    if (tenantId) {
      query += ` WHERE tenant_id = ?;`;
      params.push(tenantId);
    } else {
      query += `;`;
    }

    const rows = await adapter.query<any>(query, params);
    const row = rows[0] || {
      total_prevented: 0,
      messaging_saved_paise: 0,
      provider_saved_paise: 0,
      goodwill_saved_paise: 0,
      total_capital_saved_paise: 0,
    };

    const totalSavedPaise = Number(row.total_capital_saved_paise || 0);

    return {
      total_prevented: Number(row.total_prevented || 0),
      messaging_saved_paise: Number(row.messaging_saved_paise || 0),
      provider_saved_paise: Number(row.provider_saved_paise || 0),
      goodwill_saved_paise: Number(row.goodwill_saved_paise || 0),
      total_capital_saved_paise: totalSavedPaise,
      total_capital_saved_display: `₹${(totalSavedPaise / 100).toLocaleString(undefined, {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })}`,
    };
  }

  /**
   * Synthetic Holdout Engine: 5% of eligible opportunities are deterministically
   * assigned to holdout to continuously evaluate true counterfactual natural recovery.
   */
  public static isSyntheticHoldout(opportunityId: string): boolean {
    let hash = 0;
    for (let i = 0; i < opportunityId.length; i++) {
      hash = (hash << 5) - hash + opportunityId.charCodeAt(i);
      hash |= 0;
    }
    return Math.abs(hash) % 100 < 5; // 5% holdout
  }
}
